apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: eap-app
    template: eap73-basic-s2i
    xpaas: "7.3"
  name: eap-app
  namespace: monitor-jboss-eap
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: prometheus
    port: 9799
    protocol: TCP
    targetPort: 9799
  selector:
    deploymentConfig: eap-app
  sessionAffinity: None
  type: ClusterIP