apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-app-monitor
spec:
  endpoints:
  - interval: 30s
    port: 8080-tcp
    scheme: http
  selector:
    matchLabels:
      app: metrics-app